<?php

namespace Valantic\DataQualityBundle\Validation;

class ConstraintDefinitions
{
    public function symfony()
    {
        return [
            'All',
            'Bic',
            'Blank',
            'Callback',
            'CardScheme',
            'Choice',
            'Collection',
            'Count',
            'Country',
            'Currency',
            'Date',
            'DateTime',
            'DivisibleBy',
            'Email',
            'EqualTo',
            'Expression',
            'File',
            'GreaterThan',
            'GreaterThanOrEqual',
            'Iban',
            'IdenticalTo',
            'Image',
            'Ip',
            'IsFalse',
            'IsNull',
            'IsTrue',
            'Isbn',
            'Issn',
            'Json',
            'Language',
            'Length',
            'LessThan',
            'LessThanOrEqual',
            'Locale',
            'Luhn',
            'Negative',
            'NegativeOrZero',
            'NotBlank',
            'NotCompromisedPassword',
            'NotEqualTo',
            'NotIdenticalTo',
            'NotNull',
            'Positive',
            'PositiveOrZero',
            'Range',
            'Regex',
            'Time',
            'Timezone',
            'Traverse',
            'Type',
            'Unique',
            'UniqueEntity',
            'Url',
            'UserPassword',
            'Uuid',
            'Valid',
        ];
    }
}
